[project]
name = "pydiscolist"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
]

[dependency-groups]
dev = [
    "neovim>=0.3.1",
    "pytest>=8.3.5",
    "rope>=1.13.0",
]
